language: csharp
solution: Narivia.sln
install:
  - wget https://raw.githubusercontent.com/hmlendea/deployment-scripts/master/monogame-install.sh
  - bash monogame-install.sh
  - nuget restore
script:
  - msbuild

